### ISSUE TITLE
GB18030 not available with newest edition and ST3

### ISSUE THREAD

**Issue by ernestyao** [titoBouzout/EncodingHelper#17]
When I convert GB18030 to UTF8, I got a message "gb18030 is unknown in this system".
I'm using ST 3 build 3066 with the newest EncodingHelper now, on OS X 10.10.1.
Is there something wrong? If sample text file needed, let me know.

**Comment by ernestyao** [comment]
Is there any suggestion?
I googled and found nothing relevant about python 3 in ST3. (The change log is the top hit :( )

**Comment by titoBouzout** [comment]
I think is done @ernestyao , found a version of the codecs for Linux and OSX, please update, restart and let me know if works for you. Kind regards,

**Comment by ernestyao** [comment]
You mean should updating EncodingHelper through Package Control? I did it just now and reopened Sublime Text 3. I still get "GB18030 is unknown in this system" error. Is there something I missed?

**Comment by titoBouzout** [comment]
Yes, it should work, Remove the package, be sure is removed. Then install it again.

**Comment by ernestyao** [comment]
Yes, reinstall the package helps! Thank you, @titoBouzout

**Comment by titoBouzout** [comment]
Cool ^_^
